Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.network "forwarded_port", guest: 80, host: 8080   #HTTP
  config.vm.network "forwarded_port", guest: 443, host: 8443  #HTTPS
end
