---
- hosts: 127.0.0.1
  vars_prompt:
    - name: "vcenter_hostname"
      prompt: "Enter the IP/hostname of your vCenter"
      private: no

    - name: "vcenter_username"
      prompt: "Enter your vCenter username"
      private: no
      default: "administrator@vsphere.local"

    - name: "vcenter_password"
      prompt: "Enter your vCenter password"

    - name: "datacenter_name"
      prompt: "Enter the name for your Datacenter"
      private: no
      default: "TEST_DATACENTER"

    - name: "cluster_name"
      prompt: "Enter the name for your cluster"
      private: no
      default: "TEST_CLUSTER"

    - name: "esxi_hostname"
      prompt: "Enter the IP/hostname of your ESXi host"
      private: no

    - name: "esxi_username"
      prompt: "Enter your ESXi username"
      private: no
      default: "root"

    - name: "esxi_password"
      prompt: "Enter your ESXi password"
      
  tasks:
  - name: Add host to cluster
    vmware_host:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter_name: '{{ datacenter_name }}'
      cluster_name: '{{ cluster_name }}'
      esxi_hostname: '{{ esxi_hostname }}'
      esxi_username: '{{ esxi_username }}'
      esxi_password: '{{ esxi_password }}'
      state: present
      validate_certs: no
    delegate_to: localhost
